const CREATE_PATIENT_INSURANCES = "CREATE_PATIENT_INSURANCES";
const CREATE_PATIENT_INSURANCES_SUCCESS = "CREATE_PATIENT_INSURANCES_SUCCESS";
const CREATE_PATIENT_INSURANCES_FAILED = "CREATE_PATIENT_INSURANCES_FAILED";
const CREATE_PATIENT_INSURANCES_ERROR = "CREATE_PATIENT_INSURANCES_ERROR";

const UPDATE_PATIENT_INSURANCES = "UPDATE_PATIENT_INSURANCES";
const UPDATE_PATIENT_INSURANCES_SUCCESS = "UPDATE_PATIENT_INSURANCES_SUCCESS";
const UPDATE_PATIENT_INSURANCES_FAILED = "UPDATE_PATIENT_INSURANCES_FAILED";
const UPDATE_PATIENT_INSURANCES_ERROR = "UPDATE_PATIENT_INSURANCES_ERROR";

const DELETE_PATIENT_INSURANCES = "DELETE_PATIENT_INSURANCES";
const DELETE_PATIENT_INSURANCES_SUCCESS = "DELETE_PATIENT_INSURANCES_SUCCESS";
const DELETE_PATIENT_INSURANCES_FAILED = "DELETE_PATIENT_INSURANCES_FAILED";
const DELETE_PATIENT_INSURANCES_ERROR = "DELETE_PATIENT_INSURANCES_ERROR";

const GET_PATIENT_INSURANCES = "GET_PATIENT_INSURANCES";
const GET_PATIENT_INSURANCES_SUCCESS = "GET_PATIENT_INSURANCES_SUCCESS";
const GET_PATIENT_INSURANCES_FAILED = "GET_PATIENT_INSURANCES_FAILED";
const GET_PATIENT_INSURANCES_ERROR = "GET_PATIENT_INSURANCES_ERROR";

const state = () => ({
  showLoader: Boolean,
  insurancecards: [],
  insurancecard: {}
});



