/** SIGNin Mutations types**/
export const SIGNIN = 'SIGNIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';

export const SIGNOUT = 'SIGNOUT';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_FAILED = 'SIGNOUT_FAILED';

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const GET_PATIENTS = "GET_PATIENTS";
export const GET_PATIENTS_SUCCESS = "GET_PATIENTS_SUCCESS";
export const GET_PATIENTS_FAILED = "GET_PATIENTS_FAILED";
export const GET_PATIENTS_ERROR = "GET_PATIENTS_ERROR";

export const CREATE_PATIENTS = "CREATE_PATIENTS";
export const CREATE_PATIENTS_SUCCESS = "CREATE_PATIENTS_SUCCESS";
export const CREATE_PATIENTS_FAILED = "CREATE_PATIENTS_FAILED";
export const CREATE_PATIENTS_ERROR = "CREATE_PATIENTS_ERROR";

export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const UPDATE_PATIENT_SUCCESS = "UPDATE_PATIENT_SUCCESS";
export const UPDATE_PATIENT_FAILED = "UPDATE_PATIENT_FAILED";
export const UPDATE_PATIENT_ERROR = "UPDATE_PATIENT_ERROR";


export const DELETE_PATIENT = "DELETE_PATIENT";
export const DELETE_PATIENT_SUCCESS = "DELETE_PATIENT_SUCCESS";
export const DELETE_PATIENT_FAILED = "DELETE_PATIENT_FAILED";
export const DELETE_PATIENT_ERROR = "DELETE_PATIENT_ERROR";



export const GET_PATIENT_CREATION_TEMPLATE = "GET_PATIENT_CREATION_TEMPLATE";
export const GET_PATIENT_CREATION_TEMPLATE_SUCCESS = "GET_PATIENT_CREATION_TEMPLATE_SUCCESS";
export const GET_PATIENT_CREATION_TEMPLATE_FAILED = "GET_PATIENT_CREATION_TEMPLATE_FAILED";
export const GET_PATIENT_CREATION_TEMPLATE_ERROR = "GET_PATIENT_CREATION_TEMPLATE_ERROR";


export const UPDATE_PATIENT_PROFILE_PICTURE = "UPDATE_PATIENT_PROFILE_PICTURE";
export const UPDATE_PATIENT_PROFILE_PICTURE_SUCCESS = "UPDATE_PATIENT_PROFILE_PICTURE_SUCCESS";
export const UPDATE_PATIENT_PROFILE_PICTURE_FAILED = "UPDATE_PATIENT_PROFILE_PICTURE_FAILED";
export const UPDATE_PATIENT_PROFILE_PICTURE_ERROR = "UPDATE_PATIENT_PROFILE_PICTURE_ERROR";

export const UPLOAD_PATIENT_DOCUMENT = "UPLOAD_PATIENT_DOCUMENT";
export const UPLOAD_PATIENT_DOCUMENT_SUCCESS = "UPLOAD_PATIENT_DOCUMENT_SUCCESS";
export const UPLOAD_PATIENT_DOCUMENT_FAILED = "UPLOAD_PATIENT_DOCUMENT_FAILED";
export const UPLOAD_PATIENT_DOCUMENT_ERROR = "UPLOAD_PATIENT_DOCUMENT_ERROR";

export const UPDATE_PATIENT_ADD_CONTACT = "UPDATE_PATIENT_ADD_CONTACT";
export const UPDATE_PATIENT_ADD_CONTACT_SUCCESS = "UPDATE_PATIENT_ADD_CONTACT_SUCCESS";
export const UPDATE_PATIENT_ADD_CONTACT_FAILED = "UPDATE_PATIENT_ADD_CONTACT_FAILED";
export const UPDATE_PATIENT_ADD_CONTACT_ERROR = "UPDATE_PATIENT_ADD_CONTACT_ERROR";

export const FETCH_APPLICATION_USERS = "FETCH_APPLICATION_USERS";
export const FETCH_APPLICATION_USERS_SUCCESS = "FETCH_APPLICATION_USERS_SUCCESS";
export const FETCH_APPLICATION_USERS_FAILED = "FETCH_APPLICATION_USERS_FAILED";
export const FETCH_APPLICATION_USERS_ERROR = "FETCH_APPLICATION_USERS_ERROR";

export const SIGNUPx = "SIGNUPx";
export const SIGNUPx_SUCCESS = "SIGNUPx_SUCCESS";
export const SIGNUPx_FAILED = "SIGNUPx_FAILED";
export const SIGNUPx_ERROR = "SIGNUPx_ERROR";

