/** SIGNin Mutations types**/
export const SIGNIN = 'SIGNIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';

export const SIGNOUT = 'SIGNOUT';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_FAILED = 'SIGNOUT_FAILED';

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const GET_PATIENTS = "GET_PATIENTS";
export const GET_PATIENTS_SUCCESS = "GET_PATIENTS_SUCCESS";
export const GET_PATIENTS_FAILED = "GET_PATIENTS_FAILED";
export const GET_PATIENTS_ERROR = "GET_PATIENTS_ERROR";



export const GET_PATIENT_TRENDS = "GET_PATIENT_TRENDS";
export const GET_PATIENT_TRENDS_SUCCESS = "GET_PATIENT_TRENDS_SUCCESS";
export const GET_PATIENT_TRENDS_FAILED = "GET_PATIENT_TRENDS_FAILED";
export const GET_PATIENT_TRENDS_ERROR = "GET_PATIENT_TRENDS_ERROR";

export const CREATE_PATIENTS = "CREATE_PATIENTS";
export const CREATE_PATIENTS_SUCCESS = "CREATE_PATIENTS_SUCCESS";
export const CREATE_PATIENTS_FAILED = "CREATE_PATIENTS_FAILED";
export const CREATE_PATIENTS_ERROR = "CREATE_PATIENTS_ERROR";

export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const UPDATE_PATIENT_SUCCESS = "UPDATE_PATIENT_SUCCESS";
export const UPDATE_PATIENT_FAILED = "UPDATE_PATIENT_FAILED";
export const UPDATE_PATIENT_ERROR = "UPDATE_PATIENT_ERROR";


export const DELETE_PATIENT = "DELETE_PATIENT";
export const DELETE_PATIENT_SUCCESS = "DELETE_PATIENT_SUCCESS";
export const DELETE_PATIENT_FAILED = "DELETE_PATIENT_FAILED";
export const DELETE_PATIENT_ERROR = "DELETE_PATIENT_ERROR";



export const GET_PATIENT_CREATION_TEMPLATE = "GET_PATIENT_CREATION_TEMPLATE";
export const GET_PATIENT_CREATION_TEMPLATE_SUCCESS = "GET_PATIENT_CREATION_TEMPLATE_SUCCESS";
export const GET_PATIENT_CREATION_TEMPLATE_FAILED = "GET_PATIENT_CREATION_TEMPLATE_FAILED";
export const GET_PATIENT_CREATION_TEMPLATE_ERROR = "GET_PATIENT_CREATION_TEMPLATE_ERROR";


export const UPDATE_PATIENT_PROFILE_PICTURE = "UPDATE_PATIENT_PROFILE_PICTURE";
export const UPDATE_PATIENT_PROFILE_PICTURE_SUCCESS = "UPDATE_PATIENT_PROFILE_PICTURE_SUCCESS";
export const UPDATE_PATIENT_PROFILE_PICTURE_FAILED = "UPDATE_PATIENT_PROFILE_PICTURE_FAILED";
export const UPDATE_PATIENT_PROFILE_PICTURE_ERROR = "UPDATE_PATIENT_PROFILE_PICTURE_ERROR";

export const UPLOAD_PATIENT_DOCUMENT = "UPLOAD_PATIENT_DOCUMENT";
export const UPLOAD_PATIENT_DOCUMENT_SUCCESS = "UPLOAD_PATIENT_DOCUMENT_SUCCESS";
export const UPLOAD_PATIENT_DOCUMENT_FAILED = "UPLOAD_PATIENT_DOCUMENT_FAILED";
export const UPLOAD_PATIENT_DOCUMENT_ERROR = "UPLOAD_PATIENT_DOCUMENT_ERROR";

export const UPDATE_PATIENT_ADD_CONTACT = "UPDATE_PATIENT_ADD_CONTACT";
export const UPDATE_PATIENT_ADD_CONTACT_SUCCESS = "UPDATE_PATIENT_ADD_CONTACT_SUCCESS";
export const UPDATE_PATIENT_ADD_CONTACT_FAILED = "UPDATE_PATIENT_ADD_CONTACT_FAILED";
export const UPDATE_PATIENT_ADD_CONTACT_ERROR = "UPDATE_PATIENT_ADD_CONTACT_ERROR";

export const FETCH_APPLICATION_USERS = "FETCH_APPLICATION_USERS";
export const FETCH_APPLICATION_USERS_SUCCESS = "FETCH_APPLICATION_USERS_SUCCESS";
export const FETCH_APPLICATION_USERS_FAILED = "FETCH_APPLICATION_USERS_FAILED";
export const FETCH_APPLICATION_USERS_ERROR = "FETCH_APPLICATION_USERS_ERROR";

export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const CREATE_NEW_USER_SUCCESS = "CREATE_NEW_USER_SUCCESS";
export const CREATE_NEW_USER_FAILED = "CREATE_NEW_USER_FAILED";
export const CREATE_NEW_USER_ERROR = "CREATE_NEW_USER_ERROR";


export const GET_MEDICINE_PRODUCTS = "GET_MEDICINE_PRODUCTS";
export const GET_MEDICINE_PRODUCTS_SUCCESS = "GET_MEDICINE_PRODUCTS_SUCCESS";
export const GET_MEDICINE_PRODUCTS_FAILED = "GET_MEDICINE_PRODUCTS_FAILED";
export const GET_MEDICINE_PRODUCTS_ERROR = "GET_MEDICINE_PRODUCTS_ERROR";

export const CREATE_NEW_MEDICINE_PRODUCT = "CREATE_NEW_MEDICINE_PRODUCT";
export const CREATE_NEW_MEDICINE_PRODUCT_SUCCESS = "CREATE_NEW_MEDICINE_PRODUCT_SUCCESS";
export const CREATE_NEW_MEDICINE_PRODUCT_FAILED = "CREATE_NEW_MEDICINE_PRODUCT_FAILED";
export const CREATE_NEW_MEDICINE_PRODUCT_ERROR = "CREATE_NEW_MEDICINE_PRODUCT_ERROR";

export const UPDATE_MEDICINE_PRODUCT = "UPDATE_MEDICINE_PRODUCT";
export const UPDATE_MEDICINE_PRODUCT_SUCCESS = "UPDATE_MEDICINE_PRODUCT_SUCCESS";
export const UPDATE_MEDICINE_PRODUCT_FAILED = "UPDATE_MEDICINE_PRODUCT_FAILED";
export const UPDATE_MEDICINE_PRODUCT_ERROR = "UPDATE_MEDICINE_PRODUCT_ERROR";

export const MEDICINE_TEMPLATE = "MEDICINE_TEMPLATE";
export const MEDICINE_TEMPLATE_SUCCESS = "MEDICINE_TEMPLATE_SUCCESS";
export const MEDICINE_TEMPLATE_FAILED = "MEDICINE_TEMPLATE_FAILED";
export const MEDICINE_TEMPLATE_ERROR = "MEDICINE_TEMPLATE_ERROR";

export const ADD_NEW_DIAGNOSIS = "ADD_NEW_DIAGNOSIS";
export const ADD_NEW_DIAGNOSIS_SUCCESS = "ADD_NEW_DIAGNOSIS_SUCCESS";
export const ADD_NEW_DIAGNOSIS_FAILED = "ADD_NEW_DIAGNOSIS_FAILED";
export const ADD_NEW_DIAGNOSIS_ERROR = "ADD_NEW_DIAGNOSIS_ERROR";

export const RETRIEVE_WARDS = "RETRIEVE_WARDS";
export const RETRIEVE_WARDS_SUCCESS = "RETRIEVE_WARDS_SUCCESS";
export const RETRIEVE_WARDS_FAILED = "RETRIEVE_WARDS_FAILED";
export const RETRIEVE_WARDS_ERROR = "RETRIEVE_WARDS_ERROR";

export const GET_BEDS = "GET_BEDS";
export const GET_BEDS_SUCCESS = "GET_BEDS_SUCCESS";
export const GET_BEDS_FAILED = "GET_BEDS_FAILED";
export const GET_BEDS_ERROR = "GET_BEDS_ERROR"

export const ADMIT_PATIENT = "ADMIT_PATIENT";
export const ADMIT_PATIENT_SUCCESS = "ADMIT_PATIENT_SUCCESS";
export const ADMIT_PATIENT_FAILED = "ADMIT_PATIENT_FAILED";
export const ADMIT_PATIENT_ERROR = "ADMIT_PATIENT_ERROR"


export const END_ADMISSION = "END_ADMISSION";
export const END_ADMISSION_SUCCESS = "END_ADMISSION_SUCCESS";
export const END_ADMISSION_FAILED = "END_ADMISSION_FAILED";
export const END_ADMISSION_ERROR = "END_ADMISSION_ERROR"

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR"

export const SIGNUPx = "SIGNUPx";
export const SIGNUPx_SUCCESS = "SIGNUPx_SUCCESS";
export const SIGNUPx_FAILED = "SIGNUPx_FAILED";
export const SIGNUPx_ERROR = "SIGNUPx_ERROR"


