/** SIGNin Mutations types**/
export const SIGNIN = 'SIGNIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';

export const SIGNOUT = 'SIGNOUT';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_FAILED = 'SIGNOUT_FAILED';

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const GET_PATIENTS = "GET_PATIENTS";
export const GET_PATIENTS_SUCCESS = "GET_PATIENTS_SUCCESS";
export const GET_PATIENTS_FAILED = "GET_PATIENTS_FAILED";
export const GET_PATIENTS_ERROR = "GET_PATIENTS_ERROR";



export const GET_PATIENT_TRENDS = "GET_PATIENT_TRENDS";
export const GET_PATIENT_TRENDS_SUCCESS = "GET_PATIENT_TRENDS_SUCCESS";
export const GET_PATIENT_TRENDS_FAILED = "GET_PATIENT_TRENDS_FAILED";
export const GET_PATIENT_TRENDS_ERROR = "GET_PATIENT_TRENDS_ERROR";

export const CREATE_PATIENTS = "CREATE_PATIENTS";
export const CREATE_PATIENTS_SUCCESS = "CREATE_PATIENTS_SUCCESS";
export const CREATE_PATIENTS_FAILED = "CREATE_PATIENTS_FAILED";
export const CREATE_PATIENTS_ERROR = "CREATE_PATIENTS_ERROR";

export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const UPDATE_PATIENT_SUCCESS = "UPDATE_PATIENT_SUCCESS";
export const UPDATE_PATIENT_FAILED = "UPDATE_PATIENT_FAILED";
export const UPDATE_PATIENT_ERROR = "UPDATE_PATIENT_ERROR";


export const DELETE_PATIENT = "DELETE_PATIENT";
export const DELETE_PATIENT_SUCCESS = "DELETE_PATIENT_SUCCESS";
export const DELETE_PATIENT_FAILED = "DELETE_PATIENT_FAILED";
export const DELETE_PATIENT_ERROR = "DELETE_PATIENT_ERROR";



export const GET_PATIENT_CREATION_TEMPLATE = "GET_PATIENT_CREATION_TEMPLATE";
export const GET_PATIENT_CREATION_TEMPLATE_SUCCESS = "GET_PATIENT_CREATION_TEMPLATE_SUCCESS";
export const GET_PATIENT_CREATION_TEMPLATE_FAILED = "GET_PATIENT_CREATION_TEMPLATE_FAILED";
export const GET_PATIENT_CREATION_TEMPLATE_ERROR = "GET_PATIENT_CREATION_TEMPLATE_ERROR";


export const UPDATE_PATIENT_PROFILE_PICTURE = "UPDATE_PATIENT_PROFILE_PICTURE";
export const UPDATE_PATIENT_PROFILE_PICTURE_SUCCESS = "UPDATE_PATIENT_PROFILE_PICTURE_SUCCESS";
export const UPDATE_PATIENT_PROFILE_PICTURE_FAILED = "UPDATE_PATIENT_PROFILE_PICTURE_FAILED";
export const UPDATE_PATIENT_PROFILE_PICTURE_ERROR = "UPDATE_PATIENT_PROFILE_PICTURE_ERROR";

export const UPLOAD_PATIENT_DOCUMENT = "UPLOAD_PATIENT_DOCUMENT";
export const UPLOAD_PATIENT_DOCUMENT_SUCCESS = "UPLOAD_PATIENT_DOCUMENT_SUCCESS";
export const UPLOAD_PATIENT_DOCUMENT_FAILED = "UPLOAD_PATIENT_DOCUMENT_FAILED";
export const UPLOAD_PATIENT_DOCUMENT_ERROR = "UPLOAD_PATIENT_DOCUMENT_ERROR";

export const UPDATE_PATIENT_ADD_CONTACT = "UPDATE_PATIENT_ADD_CONTACT";
export const UPDATE_PATIENT_ADD_CONTACT_SUCCESS = "UPDATE_PATIENT_ADD_CONTACT_SUCCESS";
export const UPDATE_PATIENT_ADD_CONTACT_FAILED = "UPDATE_PATIENT_ADD_CONTACT_FAILED";
export const UPDATE_PATIENT_ADD_CONTACT_ERROR = "UPDATE_PATIENT_ADD_CONTACT_ERROR";

export const FETCH_APPLICATION_USERS = "FETCH_APPLICATION_USERS";
export const FETCH_APPLICATION_USERS_SUCCESS = "FETCH_APPLICATION_USERS_SUCCESS";
export const FETCH_APPLICATION_USERS_FAILED = "FETCH_APPLICATION_USERS_FAILED";
export const FETCH_APPLICATION_USERS_ERROR = "FETCH_APPLICATION_USERS_ERROR";

export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const CREATE_NEW_USER_SUCCESS = "CREATE_NEW_USER_SUCCESS";
export const CREATE_NEW_USER_FAILED = "CREATE_NEW_USER_FAILED";
export const CREATE_NEW_USER_ERROR = "CREATE_NEW_USER_ERROR";


export const GET_MEDICINE_PRODUCTS = "GET_MEDICINE_PRODUCTS";
export const GET_MEDICINE_PRODUCTS_SUCCESS = "GET_MEDICINE_PRODUCTS_SUCCESS";
export const GET_MEDICINE_PRODUCTS_FAILED = "GET_MEDICINE_PRODUCTS_FAILED";
export const GET_MEDICINE_PRODUCTS_ERROR = "GET_MEDICINE_PRODUCTS_ERROR";

export const CREATE_NEW_MEDICINE_PRODUCT = "CREATE_NEW_MEDICINE_PRODUCT";
export const CREATE_NEW_MEDICINE_PRODUCT_SUCCESS = "CREATE_NEW_MEDICINE_PRODUCT_SUCCESS";
export const CREATE_NEW_MEDICINE_PRODUCT_FAILED = "CREATE_NEW_MEDICINE_PRODUCT_FAILED";
export const CREATE_NEW_MEDICINE_PRODUCT_ERROR = "CREATE_NEW_MEDICINE_PRODUCT_ERROR";

export const UPDATE_MEDICINE_PRODUCT = "UPDATE_MEDICINE_PRODUCT";
export const UPDATE_MEDICINE_PRODUCT_SUCCESS = "UPDATE_MEDICINE_PRODUCT_SUCCESS";
export const UPDATE_MEDICINE_PRODUCT_FAILED = "UPDATE_MEDICINE_PRODUCT_FAILED";
export const UPDATE_MEDICINE_PRODUCT_ERROR = "UPDATE_MEDICINE_PRODUCT_ERROR";

export const MEDICINE_TEMPLATE = "MEDICINE_TEMPLATE";
export const MEDICINE_TEMPLATE_SUCCESS = "MEDICINE_TEMPLATE_SUCCESS";
export const MEDICINE_TEMPLATE_FAILED = "MEDICINE_TEMPLATE_FAILED";
export const MEDICINE_TEMPLATE_ERROR = "MEDICINE_TEMPLATE_ERROR";

export const ADD_NEW_DIAGNOSIS = "ADD_NEW_DIAGNOSIS";
export const ADD_NEW_DIAGNOSIS_SUCCESS = "ADD_NEW_DIAGNOSIS_SUCCESS";
export const ADD_NEW_DIAGNOSIS_FAILED = "ADD_NEW_DIAGNOSIS_FAILED";
export const ADD_NEW_DIAGNOSIS_ERROR = "ADD_NEW_DIAGNOSIS_ERROR";

export const GET_WARDS = "GET_WARDS";
export const GET_WARDS_SUCCESS = "GET_WARDS_SUCCESS";
export const GET_WARDS_FAILED = "GET_WARDS_FAILED";
export const GET_WARDS_ERROR = "GET_WARDS_ERROR";

export const GET_BEDS = "GET_BEDS";
export const GET_BEDS_SUCCESS = "GET_BEDS_SUCCESS";
export const GET_BEDS_FAILED = "GET_BEDS_FAILED";
export const GET_BEDS_ERROR = "GET_BEDS_ERROR"

export const ADMIT_PATIENT = "ADMIT_PATIENT";
export const ADMIT_PATIENT_SUCCESS = "ADMIT_PATIENT_SUCCESS";
export const ADMIT_PATIENT_FAILED = "ADMIT_PATIENT_FAILED";
export const ADMIT_PATIENT_ERROR = "ADMIT_PATIENT_ERROR"


export const END_ADMISSION = "END_ADMISSION";
export const END_ADMISSION_SUCCESS = "END_ADMISSION_SUCCESS";
export const END_ADMISSION_FAILED = "END_ADMISSION_FAILED";
export const END_ADMISSION_ERROR = "END_ADMISSION_ERROR"

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR"

export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILED = "UPDATE_PASSWORD_FAILED";
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR"


export const FETCH_ROLES = "FETCH_ROLES";
export const FETCH_ROLES_SUCCESS = "FETCH_ROLES_SUCCESS";
export const FETCH_ROLES_FAILED = "FETCH_ROLES_FAILED";
export const FETCH_ROLES_ERROR = "FETCH_ROLES_ERROR"

export const FETCH_STAFFS = "FETCH_STAFFS";
export const FETCH_STAFFS_SUCCESS = "FETCH_STAFFS_SUCCESS";
export const FETCH_STAFFS_FAILED = "FETCH_STAFFS_FAILED";
export const FETCH_STAFFS_ERROR = "FETCH_STAFFS_ERROR"

export const UPDATE_STAFF = "UPDATE_STAFF";
export const UPDATE_STAFF_SUCCESS = "UPDATE_STAFF_SUCCESS";
export const UPDATE_STAFF_FAILED = "UPDATE_STAFF_FAILED";
export const UPDATE_STAFF_ERROR = "UPDATE_STAFF_ERROR"


export const FETCH_BLOODS = "FETCH_BLOODS";
export const FETCH_BLOODS_SUCCESS = "FETCH_BLOODS_SUCCESS";
export const FETCH_BLOODS_FAILED = "FETCH_BLOODS_FAILED";
export const FETCH_BLOODS_ERROR = "FETCH_BLOODS_ERROR"

export const UPDATE_BLOOD = "UPDATE_BLOOD";
export const UPDATE_BLOOD_SUCCESS = "UPDATE_BLOOD_SUCCESS";
export const UPDATE_BLOOD_FAILED = "UPDATE_BLOOD_FAILED";
export const UPDATE_BLOOD_ERROR = "UPDATE_BLOOD_ERROR"

export const STATISTICS = "STATISTICS";
export const STATISTICS_SUCCESS = "STATISTICS_SUCCESS";
export const STATISTICS_FAILED = "STATISTICS_FAILED";
export const STATISTICS_ERROR = "STATISTICS_ERROR"

export const FETCH_MEDICINE_CATEGORIES = "FETCH_MEDICINE_CATEGORIES";
export const FETCH_MEDICINE_CATEGORIES_SUCCESS = "FETCH_MEDICINE_CATEGORIES_SUCCESS";
export const FETCH_MEDICINE_CATEGORIES_FAILED = "FETCH_MEDICINE_CATEGORIES_FAILED";
export const FETCH_MEDICINE_CATEGORIES_ERROR = "FETCH_MEDICINE_CATEGORIES_ERROR"

export const CREATE_MEDICINE_CATEGORY = "CREATE_MEDICINE_CATEGORY";
export const CREATE_MEDICINE_CATEGORY_SUCCESS = "CREATE_MEDICINE_CATEGORY_SUCCESS";
export const CREATE_MEDICINE_CATEGORY_FAILED = "CREATE_MEDICINE_CATEGORY_FAILED";
export const CREATE_MEDICINE_CATEGORY_ERROR = "CREATE_MEDICINE_CATEGORY_ERROR"

export const UPDATE_MEDICINE_CATEGORY = "UPDATE_MEDICINE_CATEGORY";
export const UPDATE_MEDICINE_CATEGORY_SUCCESS = "UPDATE_MEDICINE_CATEGORY_SUCCESS";
export const UPDATE_MEDICINE_CATEGORY_FAILED = "UPDATE_MEDICINE_CATEGORY_FAILED";
export const UPDATE_MEDICINE_CATEGORY_ERROR = "GET_DEPARTMENTS_ERROR";


export const FETCH_MEDICINE_GROUPS = "FETCH_MEDICINE_GROUPS";
export const FETCH_MEDICINE_GROUPS_SUCCESS = "FETCH_MEDICINE_GROUPS_SUCCESS";
export const FETCH_MEDICINE_GROUPS_FAILED = "FETCH_MEDICINE_GROUPS_FAILED";
export const FETCH_MEDICINE_GROUPS_ERROR = "FETCH_MEDICINE_GROUPS_ERROR"

export const CREATE_MEDICINE_GROUP = "CREATE_MEDICINE_GROUP";
export const CREATE_MEDICINE_GROUP_SUCCESS = "CREATE_MEDICINE_GROUP_SUCCESS";
export const CREATE_MEDICINE_GROUP_FAILED = "CREATE_MEDICINE_GROUP_FAILED";
export const CREATE_MEDICINE_GROUP_ERROR = "CREATE_MEDICINE_GROUP_ERROR"

export const UPDATE_MEDICINE_GROUP = "UPDATE_MEDICINE_GROUP";
export const UPDATE_MEDICINE_GROUP_SUCCESS = "UPDATE_MEDICINE_GROUP_SUCCESS";
export const UPDATE_MEDICINE_GROUP_FAILED = "UPDATE_MEDICINE_GROUP_FAILED";
export const UPDATE_MEDICINE_GROUP_ERROR = "UPDATE_MEDICINE_GROUP_ERROR";


export const REQUEST_PRIVILEGES = "REQUEST_PRIVILEGES";
export const REQUEST_PRIVILEGES_SUCCESS = "REQUEST_PRIVILEGES_SUCCESS";
export const REQUEST_PRIVILEGES_FAILED = "REQUEST_PRIVILEGES_FAILED";
export const REQUEST_PRIVILEGES_ERROR = "REQUEST_PRIVILEGES_ERROR"


export const DARK_THEME = "DARK_THEME";
export const LIGHT_THEME = "LIGHT_THEME";



export const CREATE_SMS_CONFIG = "CREATE_SMS_CONFIG";
export const CREATE_SMS_CONFIG_SUCCESS = "CREATE_SMS_CONFIG_SUCCESS";
export const CREATE_SMS_CONFIG_FAILED = "CREATE_SMS_CONFIG_FAILED";
export const CREATE_SMS_CONFIG_ERROR = "CREATE_SMS_CONFIG_ERROR";

export const UPDATE_SMS_CONFIG = "UPDATE_SMS_CONFIG";
export const UPDATE_SMS_CONFIG_SUCCESS = "UPDATE_SMS_CONFIG_SUCCESS";
export const UPDATE_SMS_CONFIG_FAILED = "UPDATE_SMS_CONFIG_FAILED";
export const UPDATE_SMS_CONFIG_ERROR = "UPDATE_SMS_CONFIG_ERROR";

export const GET_SMS_CONFIG = "GET_SMS_CONFIG";
export const GET_SMS_CONFIG_SUCCESS = "GET_SMS_CONFIG_SUCCESS";
export const GET_SMS_CONFIG_FAILED = "GET_SMS_CONFIG_FAILED";
export const GET_SMS_CONFIG_ERROR = "GET_SMS_CONFIG_ERROR";

export const ACTIVATE_SMS_CONFIG = "ACTIVATE_SMS_CONFIG";
export const ACTIVATE_SMS_CONFIG_SUCCESS = "ACTIVATE_SMS_CONFIG_SUCCESS";
export const ACTIVATE_SMS_CONFIG_FAILED = "ACTIVATE_SMS_CONFIG_FAILED";
export const ACTIVATE_SMS_CONFIG_ERROR = "ACTIVATE_SMS_CONFIG_ERROR";

export const GET_IPDSERVICES = "GET_IPDSERVICES";
export const GET_IPDSERVICES_SUCCESS = "GET_IPDSERVICES_SUCCESS";
export const GET_IPDSERVICES_FAILED = "GET_IPDSERVICES_FAILED";
export const GET_IPDSERVICES_ERROR = "GET_IPDSERVICES_ERROR";

export const GET_OPDSERVICES = "GET_OPDSERVICES";
export const GET_OPDSERVICES_SUCCESS = "GET_OPDSERVICES_SUCCESS";
export const GET_OPDSERVICES_FAILED = "GET_OPDSERVICES_FAILED";
export const GET_OPDSERVICES_ERROR = "GET_OPDSERVICES_ERROR";

export const CREATE_DEPARTMENT = "CREATE_DEPARTMENT";
export const CREATE_DEPARTMENT_SUCCESS = "CREATE_DEPARTMENT_SUCCESS";
export const CREATE_DEPARTMENT_FAILED = "CREATE_DEPARTMENT_FAILED";
export const CREATE_DEPARTMENT_ERROR = "CREATE_DEPARTMENT_ERROR";

export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
export const GET_DEPARTMENTS_SUCCESS = "GET_DEPARTMENTS_SUCCESS";
export const GET_DEPARTMENTS_FAILED = "GET_DEPARTMENTS_FAILED";
export const GET_DEPARTMENTS_ERROR = "GET_DEPARTMENTS_ERROR";


export const ASSIGN_STAFF_TO_DEPARTMENT = "ASSIGN_STAFF_TO_DEPARTMENT";
export const ASSIGN_STAFF_TO_DEPARTMENT_SUCCESS = "ASSIGN_STAFF_TO_DEPARTMENT_SUCCESS";
export const ASSIGN_STAFF_TO_DEPARTMENT_FAILED = "ASSIGN_STAFF_TO_DEPARTMENT_FAILED";
export const ASSIGN_STAFF_TO_DEPARTMENT_ERROR = "GET_DEPARTMENTS_ERROR";


export const SERVICES = "SERVICES";
export const SERVICES_SUCCESS = "SERVICES_SUCCESS";
export const SERVICES_FAILED = "SERVICES_FAILED";
export const SERVICES_ERROR = "GET_DEPARTMENTS_ERROR";


export const GET_MEDICINE_MEASURES = "GET_MEDICINE_MEASURES";
export const GET_MEDICINE_MEASURES_SUCCESS = "GET_MEDICINE_MEASURES_SUCCESS";
export const GET_MEDICINE_MEASURES_FAILED = "GET_MEDICINE_MEASURES_FAILED";
export const GET_MEDICINE_MEASURES_ERROR = "GET_MEDICINE_MEASURES_ERROR";


export const GET_DEPARTMENTSx = "GET_DEPARTMENTSx";
export const GET_DEPARTMENTSx_SUCCESS = "GET_DEPARTMENTSx_SUCCESS";
export const GET_DEPARTMENTSx_FAILED = "GET_DEPARTMENTSx_FAILED";
export const GET_DEPARTMENTSx_ERROR = "GET_DEPARTMENTSx_ERROR";
