/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see legal.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[1],{327:function(le,y,b){b.r(y);var w=b(335),z=b(84),ke=b(27),db=b(52);le=function(){function b(){this.mb=this.ce=this.Bb=this.Qb=null;this.re=!1}b.prototype.clear=function(){Object(ke.b)(this.Qb);this.Bb="";Object(ke.b)(this.ce);Object(ke.b)(this.mb);this.re=!1};b.prototype.vc=function(){this.Qb=[];this.ce=[];this.mb=[];this.re=!1};b.prototype.lu=function(b){for(var a="",f=0,e,h,n;f<b.length;)e=b.charCodeAt(f),9==e?(a+=String.fromCharCode(10),
f++):128>e?(a+=String.fromCharCode(e),f++):191<e&&224>e?(h=b.charCodeAt(f+1),a+=String.fromCharCode((e&31)<<6|h&63),f+=2):(h=b.charCodeAt(f+1),n=b.charCodeAt(f+2),a+=String.fromCharCode((e&15)<<12|(h&63)<<6|n&63),f+=3);return a};b.prototype.initData=function(b){this.Qb=[];this.ce=[];this.mb=[];this.re=!1;try{var a=new db.a(b);this.Bb="";a.za();if(!a.advance())return;var f=a.current.textContent;this.Bb=f=this.lu(f);Object(ke.b)(this.ce);a.advance();f=a.current.textContent;for(var e=f.split(","),h=
Object(z.a)(e);h.Gj();){var n=h.current;try{var r=parseInt(n.trim());this.ce.push(r)}catch(qe){}}Object(ke.b)(this.Qb);a.advance();f=a.current.textContent;e=f.split(",");for(var w=Object(z.a)(e);w.Gj();){n=w.current;try{r=parseFloat(n.trim()),this.Qb.push(r)}catch(qe){}}Object(ke.b)(this.mb);a.advance();f=a.current.textContent;e=f.split(",");b=[];a=[];f=0;for(var y=Object(z.a)(e);y.Gj();){n=y.current;switch(n){case "Q":f=1;break;case "R":f=2;break;case "S":f=3;break;default:f=0}if(f)b.push(0),a.push(f);
else try{r=parseFloat(n.trim()),b.push(r),a.push(f)}catch(qe){return}}f=0;var le=b.length;for(y=n=e=0;y<le;){var te=a[y];if(0<te)f=te,++y,3===f&&(e=b[y],n=b[y+1],y+=2);else if(1===f)for(r=0;8>r;++r)this.mb.push(b[y++]);else if(2===f){var ue=b[y++];var se=b[y++];var Ce=b[y++];var ye=b[y++];this.mb.push(ue);this.mb.push(se);this.mb.push(Ce);this.mb.push(se);this.mb.push(Ce);this.mb.push(ye);this.mb.push(ue);this.mb.push(ye)}else 3===f&&(ue=b[y++],se=e,Ce=b[y++],ye=n,this.mb.push(ue),this.mb.push(se),
this.mb.push(Ce),this.mb.push(se),this.mb.push(Ce),this.mb.push(ye),this.mb.push(ue),this.mb.push(ye))}}catch(qe){return}this.Bb.length&&this.Bb.length===this.ce.length&&8*this.Bb.length===this.mb.length&&(this.re=!0)};b.prototype.ready=function(){return this.re};b.prototype.Mr=function(){var b=new w.a;if(!this.Qb.length)return b.Uf(this.Qb,-1,this.Bb,this.mb,0),b;b.Uf(this.Qb,1,this.Bb,this.mb,1);return b};b.prototype.Ze=function(){return this.mb};return b}();y["default"]=le},335:function(le,y,b){var w=
b(50),z=b(180),ke=b(348);le=function(){function b(){this.Fd=0;this.cb=this.wa=this.ye=null;this.tc=0;this.Ed=null}b.prototype.vc=function(){this.Fd=-1;this.tc=0;this.Ed=[]};b.prototype.Uf=function(b,h,a,f,e){this.Fd=h;this.tc=e;this.Ed=[];this.ye=b;this.wa=a;this.cb=f};b.prototype.Ga=function(b){return this.Fd===b.Fd};b.prototype.Xh=function(){return Math.abs(this.ye[this.Fd])};b.prototype.Dj=function(){return 0<this.ye[this.Fd]};b.prototype.Ac=function(){var b=this.Dj()?6:10,h=new ke.a;h.Uf(this.ye,
this.Fd+b,this.Fd,this.wa,this.cb,1);return h};b.prototype.mJ=function(b){if(0>b||b>=this.Xh()){var h=new ke.a;h.Uf(this.ye,-1,-1,this.wa,this.cb,0);return h}var a=this.Dj()?6:10,f=this.Dj()?5:11;h=new ke.a;h.Uf(this.ye,this.Fd+a+f*b,this.Fd,this.wa,this.cb,1+b);return h};b.prototype.Af=function(){var r=this.Fd+parseInt(this.ye[this.Fd+1]);if(r>=this.ye.length){var h=new b;h.Uf(this.ye,-1,this.wa,this.cb,0);return h}h=new b;h.Uf(this.ye,r,this.wa,this.cb,this.tc+1);return h};b.prototype.bc=function(b){if(this.Dj())b.fa=
this.ye[this.Fd+2+0],b.ba=this.ye[this.Fd+2+1],b.ga=this.ye[this.Fd+2+2],b.ca=this.ye[this.Fd+2+3];else{for(var h=1.79769E308,a=w.a.MIN,f=1.79769E308,e=w.a.MIN,r=0;4>r;++r){var n=this.ye[this.Fd+2+2*r],y=this.ye[this.Fd+2+2*r+1];h=Math.min(h,n);a=Math.max(a,n);f=Math.min(f,y);e=Math.max(e,y)}b.fa=h;b.ba=f;b.ga=a;b.ca=e}};b.prototype.Uh=function(){if(this.Ed.length)return this.Ed[0];var b=new z.a,h=new z.a,a=new ke.a;a.vc();var f=this.Ac(),e=new ke.a;e.vc();for(var w=this.Ac();!w.Ga(a);w=w.Xe())e=
w;a=Array(8);w=Array(8);f.oe(0,a);b.x=(a[0]+a[2]+a[4]+a[6])/4;b.y=(a[1]+a[3]+a[5]+a[7])/4;e.oe(e.Tc()-1,w);h.x=(w[0]+w[2]+w[4]+w[6])/4;h.y=(w[1]+w[3]+w[5]+w[7])/4;.01>Math.abs(b.x-h.x)&&.01>Math.abs(b.y-h.y)&&this.Ed.push(0);b=Math.atan2(h.y-b.y,h.x-b.x);b*=180/3.1415926;0>b&&(b+=360);this.Ed.push(b);return 0};return b}();y.a=le},348:function(le,y,b){var w=b(335),z=b(100),ke=b(50);le=function(){function b(){this.Mi=this.jd=0;this.cb=this.wa=this.Qb=null;this.tc=0}b.prototype.vc=function(){this.Mi=
this.jd=-1;this.tc=0};b.prototype.Uf=function(b,h,a,f,e,w){this.jd=h;this.Mi=a;this.Qb=b;this.wa=f;this.cb=e;this.tc=w};b.prototype.Ga=function(b){return this.jd===b.jd};b.prototype.Tc=function(){return parseInt(this.Qb[this.jd])};b.prototype.dh=function(){return parseInt(this.Qb[this.jd+2])};b.prototype.Db=function(){return parseInt(this.Qb[this.jd+1])};b.prototype.Dj=function(){return 0<this.Qb[this.Mi]};b.prototype.yU=function(){return Math.abs(this.Qb[this.Mi])};b.prototype.Xe=function(){var r=
this.Dj(),h=r?5:11;if(this.jd>=this.Mi+(r?6:10)+(this.yU()-1)*h)return r=new b,r.Uf(this.Qb,-1,-1,this.wa,this.cb,0),r;r=new b;r.Uf(this.Qb,this.jd+h,this.Mi,this.wa,this.cb,this.tc+1);return r};b.prototype.XT=function(b){var h=this.Tc();return 0>b||b>=h?-1:parseInt(this.Qb[this.jd+1])+b};b.prototype.oe=function(b,h){b=this.XT(b);if(!(0>b)){var a=new w.a;a.Uf(this.Qb,this.Mi,this.wa,this.cb,0);if(a.Dj()){var f=new z.a;a.bc(f);a=f.ba<f.ca?f.ba:f.ca;f=f.ba>f.ca?f.ba:f.ca;b*=8;h[0]=this.cb[b];h[1]=a;
h[2]=this.cb[b+2];h[3]=h[1];h[4]=this.cb[b+4];h[5]=f;h[6]=this.cb[b+6];h[7]=h[5]}else for(b*=8,a=0;8>a;++a)h[a]=this.cb[b+a]}};b.prototype.Md=function(b){var h=new w.a;h.Uf(this.Qb,this.Mi,this.wa,this.cb,0);if(h.Dj()){var a=this.Qb[this.jd+3],f=this.Qb[this.jd+4];if(a>f){var e=a;a=f;f=e}e=new z.a;h.bc(e);h=e.ba<e.ca?e.ba:e.ca;e=e.ba>e.ca?e.ba:e.ca;b[0]=a;b[1]=h;b[2]=f;b[3]=h;b[4]=f;b[5]=e;b[6]=a;b[7]=e}else for(a=this.jd+3,f=0;8>f;++f)b[f]=this.Qb[a+f]};b.prototype.bc=function(b){var h=new w.a;h.Uf(this.Qb,
this.Mi,this.wa,this.cb,0);if(h.Dj()){var a=this.Qb[this.jd+3],f=this.Qb[this.jd+4];if(a>f){var e=a;a=f;f=e}e=new z.a;h.bc(e);h=e.ba<e.ca?e.ba:e.ca;e=e.ba>e.ca?e.ba:e.ca;b[0]=a;b[1]=h;b[2]=f;b[3]=e}else{a=1.79769E308;f=ke.a.MIN;h=1.79769E308;e=ke.a.MIN;for(var r=this.jd+3,n=0;4>n;++n){var y=this.Qb[r+2*n],db=this.Qb[r+2*n+1];a=Math.min(a,y);f=Math.max(f,y);h=Math.min(h,db);e=Math.max(e,db)}b[0]=a;b[1]=h;b[2]=f;b[3]=e}};return b}();y.a=le}}]);}).call(this || window)
